import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { getAllTraining, getTrainingBtType, Iworkout } from '../../lib/db'
import { Router, useRouter } from 'next/router'



import Avvvatars from 'avvvatars-react'
import { useState } from 'react';
import { WorkoutBox } from '../../components/WorkoutBox'
import { Line, Profile, Training } from '../../components/styles'
import { WorkoutContainer } from '../../components/trainingStyles'

interface PostProps {
  workout: Iworkout[];
}

export default function PageTraining({ workout }: PostProps) {
  const [isActive, setIsActive] = useState(false)
  const [typeTraining, setTypeTraining] = useState('')
  const router = useRouter()

  function handleGetTraining(data: string) {
    //setTypeTraining('/api/workouts/C')
    router.push(`/training?workout=${data}`)
  }

  function handleCheckWorkingOnTraining() {
    setIsActive(!isActive)
  }

  return (
    <div className='w-full h-screen flex flex-col items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='mt-4 flex p-2 gap-2'>
        <h1 className=''>Choose a Training Type</h1>
        <select
          value={typeTraining}
          onChange={e => handleGetTraining(e.target.value)}
          className='text-gray-400 bg-black'

        >
          <option value="X">Training</option>
          <option value="A">Training A</option>
          <option value="B">Training B</option>
          <option value="C">Training C</option>
        </select>
      </div>
      <div className='w-auto m-4'>
        {workout.map(item => (
          <div key={item.id}>
            <WorkoutContainer variant={isActive} onClick={handleCheckWorkingOnTraining}>


              <Profile>
                <Avvvatars value={item.type} size={48} />
                <div className="pl-3">
                  <div className="font-medium text-gray-500">
                    Luciano Mendes
                  </div>
                  <div className="text-gray-600 text-sm">
                    Personal. Jair
                  </div>
                </div>

              </Profile>
              <Line />
              <Training>
                <h2>Workout: {item.title}</h2>
                <span>{item.description}</span>
              </Training>

            </WorkoutContainer>
          </div>
        ))}
      </div>



    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req, query }) => {

  const slug = query.workout
  console.log(slug)
  const workout = await getTrainingBtType(String(slug));

  return {
    props: {
      workout,
    }
  }
}