
import Head from 'next/head'


export default function Home() {


  return (
    <div className='w-full h-screen flex flex-col items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Training</h1>


    </div>
  )
}

// export const getServerSideProps: GetServerSideProps = async ({ req, query }) => {

//   const slug = query
//   console.log(slug)
//   const workout = await getTrainingBtType(String(slug));

//   return {
//     props: {
//       workout,
//     }
//   }
// }